name    'krisbuytaert-dashing'
version '0.0.1'
source 'UNKNOWN'
author 'krisbuytaert'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
