#!/bin/bash
#Van Dyck Sven: init script for carbon
# chkconfig: - 58 74
# description: The carbon data collector for whisper and graphite.


prog=carbon

start() {
         /usr/bin/python /opt/graphite/bin/carbon-cache.py start

}

stop() {
         /usr/bin/python /opt/graphite/bin/carbon-cache.py stop
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        /usr/bin/python /opt/graphite/bin/carbon-cache.py status
        ;;
  restart|force-reload)
        stop
        sleep 5
        start
        ;;
  try-restart|condrestart)
        echo "not supported"
        exit 3
        ;;
  reload)

        echo "not supported"
        exit 3
        ;;
  *)
        echo $"Usage: $0 {start|stop|status}"
        exit 2
esac


